In [2]:
# numpy mudule is made on c language the functions it provides works very fast compared to list
# axis 0 row and axis 1 col
import numpy as np

In [76]:
# creating array

arr = np.array([[[1, 2, 3], [4, 4, 6]], [[3, 2, 1], [5, 4, 3]]])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[[1, 2, 3],
        [4, 4, 6]],

       [[3, 2, 1],
        [5, 4, 3]]])

In [77]:
# array slicing arr[0, 1] / 

print(arr.ndim)
print(arr.shape)
print(arr[:, 0])

3
(2, 2, 3)
[[1 2 3]
 [3 2 1]]


In [92]:
# setting dimensions
diarr = np.array([[1, 2, 3]], ndmin=2)
print(diarr)
print(diarr.ndim)

print('======'*20)

# reshaping array
diarr = np.array([[1, 2, 3, 4], [4, 5, 6, 4]])
print(diarr.shape)
diarr1 = diarr.reshape(2, 2, 2)
print('reshaped arr :-\n', diarr1, diarr1.ndim)
print(diarr1.base, '<-- base')

print('======'*20)

# flatten the array
diarr = diarr.reshape(-1)
print(diarr)

[[1 2 3]]
2
(2, 4)
reshaped arr :-
 [[[1 2]
  [3 4]]

 [[4 5]
  [6 4]]] 3
[[1 2 3 4]
 [4 5 6 4]] <-- base
[1 2 3 4 4 5 6 4]


In [97]:
# faltten func
print(arr)
print()

print(arr.flatten())
# or
print(arr.reshape(-1))

[[[1 2 3]
  [4 4 6]]

 [[3 2 1]
  [5 4 3]]]

[1 2 3 4 4 6 3 2 1 5 4 3]
[1 2 3 4 4 6 3 2 1 5 4 3]


In [63]:
# astype function 
newarr = np.array([[1.2, 4.6, 2.7], 
                  [5.6, 8.9, 3.7]])

print(newarr)
print(newarr.dtype)

newarr = newarr.astype(int)

print('====='*20)
print(newarr)
print(newarr.dtype)

[[1.2 4.6 2.7]
 [5.6 8.9 3.7]]
float64
[[1 4 2]
 [5 8 3]]
int32


In [72]:
# copy array

cparr = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
cparr2 = cparr # both will change
cparr[0, 1] = 10
print(cparr)
print(cparr2)

print('======'*20)

cparr = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
cparr2 = cparr.copy() # copy won't change
cparr[0, 1] = 10
print(cparr)
print(cparr2)
print(cparr2.base, '<-- check base arr')

print('======'*20)

cparr = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
cparr2 = cparr.view() # both will change
cparr[0, 1] = 10
print(cparr)
print(cparr2)
print(cparr2.base, '<-- check base arr')


[[ 1 10  3  4  5]
 [ 5  4  3  2  1]]
[[ 1 10  3  4  5]
 [ 5  4  3  2  1]]
[[ 1 10  3  4  5]
 [ 5  4  3  2  1]]
[[1 2 3 4 5]
 [5 4 3 2 1]]
None <-- check base arr
[[ 1 10  3  4  5]
 [ 5  4  3  2  1]]
[[ 1 10  3  4  5]
 [ 5  4  3  2  1]]
[[ 1 10  3  4  5]
 [ 5  4  3  2  1]] <-- check base arr


In [113]:
# iteration
print(arr)

# for loop iteration for arr
for i in arr:
    for j in i:
        for k in j:
            print(k)
            
print('====='*20)

# nditer for iteration
for i in np.nditer(arr):
    print(i)
    
# or

for i, x in np.ndenumerate(arr):
    print(i, x)

[[[1 2 3]
  [4 4 6]]

 [[3 2 1]
  [5 4 3]]]
1
2
3
4
4
6
3
2
1
5
4
3
1
2
3
4
4
6
3
2
1
5
4
3
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 4
(0, 1, 2) 6
(1, 0, 0) 3
(1, 0, 1) 2
(1, 0, 2) 1
(1, 1, 0) 5
(1, 1, 1) 4
(1, 1, 2) 3


In [17]:
# concatenate
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[3, 2, 0]])

print(arr1)
print(arr2)
print('======'*19)
print(np.concatenate((arr1, arr2), axis=0))
print('======'*19)

[[1 2 3]]
[[3 2 0]]
[[1 2 3]
 [3 2 0]]


In [24]:
# concatenate with stack func
# didnt unserstood.. for now moving on!!
print(np.concatenate((arr1, arr2)))
print('======'*18)
print(np.stack((arr1, arr2)))
print('======'*18)
print(np.hstack((arr1, arr2)))
print('======'*18)
print(np.vstack((arr1, arr2)))
print('======'*18)
print(np.dstack((arr1, arr2)))

[[1 2 3]
 [3 2 0]]
[[[1 2 3]]

 [[3 2 0]]]
[[1 2 3 3 2 0]]
[[1 2 3]
 [3 2 0]]
[[[1 3]
  [2 2]
  [3 0]]]


In [43]:
# array spliting
sparr = np.array([1, 2, 3, 4, 5, 6])
print(np.array_split(sparr, 3))
print(np.array_split(sparr, 4))
print(np.array_split(sparr, 5))
print('============'*7)

sparr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(np.array_split(sparr, 2))
print(np.array_split(sparr, 2, axis=1))
# the hsplit, vsplit, dsplit also work....

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([1, 2]), array([3]), array([4]), array([5]), array([6])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [66]:
# searching in arr
# returns index
sarr = np.array([1, 2, 3, 4, 4, 6])
print(np.where(sarr == 4))

sarr = np.array([[1, 2, 3], [3, 2, 1]])
print(np.where(sarr % 2 == 0))

print('======'*14)
sarr = np.array([6, 5, 4, 3, 2, 1])
print(np.searchsorted(sarr, 4))

# sorting
print(np.sort(sarr))

(array([3, 4], dtype=int64),)
(array([0, 1], dtype=int64), array([1, 1], dtype=int64))
6
[1 2 3 4 5 6]


In [71]:
# filter array
arr = np.array([2, 4, 6, 1, 3, 5])
print(arr[(arr % 2) != 0])

[1 3 5]


In [4]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64
